### ISSUE TITLE
Runner failed to start with custom Pod spec

### ISSUE THREAD

**Issue by missedone** [summerwind/actions-runner-controller#13]
with version 0.4.0 (PR #7), Runner failed to start with custom Pod spec
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: my-runner
  annotations:
    iam.amazonaws.com/role: my-role
spec:
  replicas: 1
  template:
    spec:
      repository: example/repo
      containers:
        - name: runner
          image: example/custom-action-runner:latest
          imagePullPolicy: Always
```

Error log
> kubectl logs muy-runner-8gcph-v7plj -f
RUNNER_NAME must be set

a fix PR will follow up soon.
