### ISSUE TITLE
v0.11.0 is broken?

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#166]
**tag** v0.11.0
**Scenario** I've deployed v0.11.0 on our EKS cluster and I get the following reconciler error. I installed the non-runner pieces by simply taking the release yaml and wrapping it in helm. I did the same for the runners.
**Notes** I've had a few versions of this running previously and not had this error so I think it is a 0.11.0.
**Debug Command** `kubectl logs $MANAGER_POD_NAME -c manager`
**Error :**

```json
2020-11-10T21:13:05.615Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "runner", "request": "sre-actions-runner-system/sre-github-runners-runner-deployment-5g58j-rbjtk", "error": "Runner.actions.summerwind.dev \"sre-github-runners-runner-deployment-5g58j-rbjtk\" is invalid: status.registration.expiresAt: Invalid value: \"null\": status.registration.expiresAt in body must be of type string: \"null\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
2020-11-10T21:13:05.675Z	DEBUG	controllers.HorizontalRunnerAutoscaler	Calculated desired replicas	{"computed_replicas_desired": 1, "spec_replicas_min": 1, "spec_replicas_max": 10, "workflow_runs_completed": 33, "workflow_runs_in_progress": 0, "workflow_runs_queued": 0, "workflow_runs_unknown": 0}
2020-11-10T21:13:05.682Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "horizontalrunnerautoscaler", "request": "sre-actions-runner-system/sre-github-runners-autoscaler"}
```

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sre-github-runners-runner-deployment
  namespace: sre-actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: my-org
      serviceAccountName: sre-github-actions-service-account
      env:
      - name: AWS_ROLE_ARN
        value: arn:aws:iam::373378159773:role/eksctl-sre-eks-test-addon-iamserviceaccount-Role1-1244USHBUKLEY
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      volumeMounts:
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token 
        readOnly: true
      volumes:
      - name: aws-iam-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
      securityContext:
        fsGroup: 27
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: sre-github-runners-autoscaler
  namespace: sre-actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleUp: 10
  scaleTargetRef:
    name: sre-github-runners-runner-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - callum-test-repo
    - callum-test-repo-2
```

Additionally I think the runner version is quite old at this point? Latest GitHub runner is at version v2.274.1 https://github.com/actions/runner/releases. Makefile uses 2.273.5 and the docker image references 2.272.0 . I'd create a PR to just bump the version but I'm not entirely sure how to test it?

**tag** v0.9.5
**Scenario** I've rolled back to v0.9.5 redeploying everyhing on our EKS cluster and I get the following error.
**Debug Command** `kubectl logs $MANAGER_POD_NAME -c manager`
**Error :**

```json
2020-11-10T21:45:44.602Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "sre-actions-runner-system/sre-github-runners-runner-deployment-25l2h-6kd9m"}
2020-11-10T21:45:44.832Z	ERROR	controllers.Runner	Failed to check if runner is busy	{"runner": "sre-actions-runner-system/sre-github-runners-runner-deployment-25l2h-6kd9m", "error": "runner not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/summerwind/actions-runner-controller/controllers.(*RunnerReconciler).Reconcile
	/workspace/controllers/runner_controller.go:212
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
2020-11-10T21:45:44.832Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "runner", "request": "sre-actions-runner-system/sre-github-runners-runner-deployment-25l2h-6kd9m"}
```
