### ISSUE TITLE
Docker daemon permissions

### ISSUE THREAD

**Issue by droidpl** [summerwind/actions-runner-controller#174]
First of all thanks for this amazing project! 🤟 

I have been trying to spin this up in an EKS cluster and almost everything has worked correctly except when I try to run docker  actions in my workflows. I've reviewed https://github.com/summerwind/actions-runner-controller/issues/138 and doesn't seem to help in my case.

## Spens
I am using the latest 0.11.2 version of the controller
EKS on 1.18 (4xt3.medium)
Default runner image with no customizations

## Tests
The action I am running is a really simple hello world that works on cloud runners. Tested it with DiD option but both fail.

**Without `dockerdWithinRunnerContainer: false`**: 
![Screen Shot 2020-11-11 at 5 53 59 PM](https://user-images.githubusercontent.com/2143931/98840332-f4e6a900-2446-11eb-9727-c5aaca0735c5.png)
```
Run ./.github/actions/hello-docker-action
  with:
    who-to-greet: Mona the Octocat
Building docker image
  Dockerfile for action: '/runner/_work/aws-deployment/aws-deployment/./.github/actions/hello-docker-action/Dockerfile'.
  /usr/local/bin/docker build -t 60e226:b93535436b0153a01b30506bd7f909c2 -f "/runner/_work/aws-deployment/aws-deployment/./.github/actions/hello-docker-action/Dockerfile" "/runner/_work/aws-deployment/aws-deployment/.github/actions/hello-docker-action"
  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=3g7trqn404lc92w7lth5a6wb3&shmsize=0&t=60e226%3Ab93535436b0153a01b30506bd7f909c2&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
Error: Docker build failed with exit code 1
```

**With `dockerdWithinRunnerContainer: true`**
![Screen Shot 2020-11-11 at 5 53 51 PM](https://user-images.githubusercontent.com/2143931/98840323-f31ce580-2446-11eb-81bc-79fc92f1e4a0.png)
```
Run ./.github/actions/hello-docker-action
  with:
    who-to-greet: Mona the Octocat
Building docker image
  Dockerfile for action: '/runner/_work/aws-deployment/aws-deployment/./.github/actions/hello-docker-action/Dockerfile'.
  /usr/local/bin/docker build -t 60e226:b93535436b0153a01b30506bd7f909c2 -f "/runner/_work/aws-deployment/aws-deployment/./.github/actions/hello-docker-action/Dockerfile" "/runner/_work/aws-deployment/aws-deployment/.github/actions/hello-docker-action"
  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: Docker build failed with exit code 1
```

## K8s configuration used
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runner
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      group: test
      organization: droidpl-demorg
      dockerdWithinRunnerContainer: true|false
      scaleDownDelaySecondsAfterScaleUp: 1m
      labels:
        - aws
        - linux
      imagePullPolicy: Always
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: test-autoscaler
spec:
  scaleTargetRef:
    name: test-runner
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - aws-deployment
```

## Actions workflow
```
on: [push, workflow_dispatch]

jobs:
  docker-job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/hello-docker-action
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
```

/cc @mumoshu as you were involved in  #138 and may have some more context
