### ISSUE TITLE
Runner image Error/Bug: OCI runtime exec failed: exec failed

### ISSUE THREAD

**Issue by erikkn** [summerwind/actions-runner-controller#190]
Hey, guys!

I was hoping the community could help me out with the following issue I am facing. I have been troubleshooting this error quite a lot with custom images etc. but I amrunning out of ideas. Please note that I am having this issue with the default (`summerwind/actions-runner`) image as well with custom images. 

## General information:
Running on: AWS EKS (managed-node-groups)
EKS version: v1.18.8-eks
Controller deployment template image: summerwind/actions-runner-controller:v0.11.3

My runner.yaml
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: gha-runner
spec:
  replicas: 2
  template:
    spec:
      labels:
        - eks-runner
      organization: "<org name>"
      dockerdWithinRunnerContainer: false
      image: <check below>
```

Due to this (https://github.com/summerwind/actions-runner-controller/issues/174) issue, I decided to use the Dockerfile specified in that same issue (https://github.com/summerwind/actions-runner-controller/issues/174#issuecomment-725598859):

```
FROM summerwind/actions-runner

# Fix the permission issue on the docker containers
COPY permissions.sh /runner

CMD /runner/permissions.sh && /runner/entrypoint.sh
```

## Reproduce steps

When I deploy my `runner.yaml` the `RunnerDeployments` looks fine. When I `exec` into my runner container and docker container, I am able to run the Docker commands e.g. docker ps, docker run ubuntu:latest).
I double-checked Docker by using a very simple custom workflow that pulls, build, runs 'echo hello world', and pushes a Docker image and that all works fine. 

However, when I run this workflow, I am getting the error as shown at the bottom.

```
name: Build, Test & Upload Service

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build_service:
    name: Build 
    runs-on: [self-hosted]
    container: <custom image>

    steps:
      - uses: actions/checkout@v2
      - name: Checkstyle Main
        run: ./gradlew checkstyleMain --info
      - name: Checkstyle Test
        run: ./gradlew checkstyleTest --info
      - name: Checkstyle Integration Test
        run: ./gradlew checkstyleIntegrationTest --info
```

## Expected behavior
Job runs fine.

## Actual behavior / Error

```
/usr/local/bin/docker exec  0712ca6bb1f7951bd47b4e43a7c86611e41ea24042a80e4c01192869a6d50322 sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/__e/node12/bin/node\": stat /__e/node12/bin/node: no such file or directory": unknown
```

When running the workflow/job I receive the error shown above. Installing nodejs in the runner image doesn't fix this issue. 
Using this (https://github.com/actions/checkout/issues/334#issuecomment-716068696) suggestion, by making some manual changes to the runner and running (kubectl exec) `/__e/node12/bin/node --version` the output looks fine. Unfortunately, after running the workflow I receiveive the same error.
