### ISSUE TITLE
Setup actions like setup-python that depend on toolcache don't work

### ISSUE THREAD

**Issue by jeffj254** [summerwind/actions-runner-controller#207]
We've been experimenting with the runner controller and have run into problems trying to use setup actions to install tools not available on the default actions-runner image.  The README makes it sound like this is expected to work, but when we try to use actions/setup-python to install Python 3.8.6 we get errors like:

```
Run actions/setup-python@v2
Version 3.8 was not found in the local cache
Version 3.8 is available for downloading
Download from "https://github.com/actions/python-versions/releases/download/3.8.6-86952/python-3.8.6-linux-18.04-x64.tar.gz"
Extract downloaded archive
/bin/tar xz --warning=no-unknown-keyword -C /runner/_work/_temp/0f003edb-caff-4018-929e-3c2d946ee037 -f /runner/_work/_temp/0dd0919a-39a5-454f-be8b-fc95bb62f759
Execute installation script
Check if Python hostedtoolcache folder exist...
Creating Python hostedtoolcache folder...
Create Python 3.8.6 folder
Copy Python binaries to hostedtoolcache folder
Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
Upgrading PIP...
##[error]./python: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
##[error]The process '/bin/bash' failed with exit code 127
```

Experimenting with this, I have found that on the official Actions virtual environment images there are some environment variables and paths that are created to support the toolcache functionality in the setup actions.  It looks like the path `/opt/hostedtoolcache` is expected to exist with `777` permissions. 

 If I manually run a bash prompt on the actions-runner image and create /opt/hostedtoolcache with 777 permissions, I'm then able to successfully run the setup.sh installation script as the `runner` user that is failing during setup-python.

It seems like this issue could be resolved by adding the folder creation and permissions to the actions-runner image, but I was curious if anyone else had run into this same issue and had a different fix before I filed a PR against the Dockerfile

**Comment by ZacharyBenamram** [comment]
Are you running GitHub Enterprise?

**Comment by jeffj254** [comment]
Yes

**Comment by ZacharyBenamram** [comment]
The version `actions/setup-python@v2` that has been installed on your ghe is most likely an older version of whats currently on the main branch at https://github.com/actions/setup-python. My recommendation is to fork the repo to your ghe instance, check-out the action via actions/checkout@v2 and then invoke the main branch. Something like:

```
- name: Checkout YOUR_ORG/setup-python
      uses: actions/checkout@v2
      with:
        repository: YOUR_ORG/setup-python
        ref: main
        path: ./.github/actions/setup-python
        token: ${{ secrets.REPO_CHECKOUT_TOKEN }}

    - name: Setup python
      uses: ./.github/actions/setup-python
      with:
        python-version: '3.6.12'
```
