### ISSUE TITLE
issue with latest summerwind/actions-runner failing to start: ./externals/node12/bin/node: No such file or directory

### ISSUE THREAD

**Issue by lasse-aagren** [summerwind/actions-runner-controller#209]
Hi,

Latest version of summerwind/actions-runner (deployed 10 hours ago) seem to be broken on actions-runner-controller v0.12.0 (0.13.0 yaml is missing in release - you have other ticket on that)

When deploying runner like:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sample-runner
spec:
  replicas: 5
  template:
    spec:
      organization: someorg
      group: All
      env: []
```
logs from a single runner ends like:
```
A runner exists with the same name
√ Successfully replaced the runner
√ Runner connection is good

# Runner settings


√ Settings Saved.

mv: target './externals/' is not a directory
16c16
< ./externals/node12/bin/node ./bin/RunnerService.js &
---
> ./externals/node12/bin/node ./bin/RunnerService.js $* &
20c20
< wait $PID
---
> wait $PID
\ No newline at end of file
27c27
<                 listener = childProcess.spawn(listenerExePath, ['run'], { env: process.env });
---
>                 listener = childProcess.spawn(listenerExePath, ['run'].concat(process.argv.slice(3)), { env: process.env });
30c30
<                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'], { env: process.env });
---
>                 listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'].concat(process.argv.slice(2)), { env: process.env });
34c34
<
---
>
59c59
<
---
>
91c91
< });
---
> });
\ No newline at end of file
.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/runner/bin/runsvc.sh: line 16: ./externals/node12/bin/node: No such file or directory
```
