### ISSUE TITLE
Old runnerReplicaSet is still alive with new runnerReplicaSet when using command 'kubectl edit'

### ISSUE THREAD

**Issue by naka-gawa** [summerwind/actions-runner-controller#24]
Hai, i use this tool for my project!
Thank you for this greatest tool!!

By the way, i have a question.
When i tried the rollout of runnerDeployment by change the image-tag, old runnerReplicaSet is still alive with new runnerReplicaSet.
Is this behavior expected?

 runnerDeployment’s manifest:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runnerDeployment
spec:
  replicas: 3
  template:
    spec:
      image: naka-gawa/runner:1.0
      repository: naka-gawa/actions-runner-controller
      env: []
```

 before status:
```
$ kubectl get runnerdeployment
NAME               DESIRED   CURRENT   READY
k8s-runnerdeploy   3

$ kubectl get runnerreplicaset
NAME                     DESIRED   CURRENT   READY
k8s-runnerdeploy-vqfbd   3         3         3

$ kubectl get runner
NAME                           REPOSITORY                            STATUS
k8s-runnerdeploy-vqfbd-5gqjw   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-vqfbd-6jmzl   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-vqfbd-knr9g   naka-gawa/actions-runner-controller   Running

$ kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
k8s-runnerdeploy-vqfbd-5gqjw   2/2     Running   0          5m23s
k8s-runnerdeploy-vqfbd-6jmzl   2/2     Running   0          5m22s
k8s-runnerdeploy-vqfbd-knr9g   2/2     Running   0          5m22s
```

 step to reproduce:
```yaml
$ kubectl edit runnerDeployment k8s-runner
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runnerDeployment
spec:
  replicas: 3
  template:
    spec:
      envFrom:
      - configMapRef:
          name: env
      image: naka-gawa/runner:1.0 -> 1.1 # Changed!!
      repository: naka-gawa/actions-runner-controller
```

 after status:
```
$ kubectl get runnerdeployment
NAME               DESIRED   CURRENT   READY
k8s-runnerdeploy   3

$ kubectl get runnerreplicaset
NAME                     DESIRED   CURRENT   READY
k8s-runnerdeploy-gdwtf   3         3         3 <<< new
k8s-runnerdeploy-vqfbd   3         3         3 <<< old

$ kubectl get runner
NAME                           REPOSITORY                            STATUS
k8s-runnerdeploy-gdwtf-5zxvw   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-gdwtf-jwcpq   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-gdwtf-zklk7   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-vqfbd-5gqjw   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-vqfbd-6jmzl   naka-gawa/actions-runner-controller   Running
k8s-runnerdeploy-vqfbd-knr9g   naka-gawa/actions-runner-controller   Running

$ kubectl get pod
NAME                           READY   STATUS    RESTARTS   AGE
k8s-runnerdeploy-gdwtf-5zxvw   2/2     Running   0          118s
k8s-runnerdeploy-gdwtf-jwcpq   2/2     Running   0          118s
k8s-runnerdeploy-gdwtf-zklk7   2/2     Running   0          118s
k8s-runnerdeploy-vqfbd-5gqjw   2/2     Running   0          9m24s
k8s-runnerdeploy-vqfbd-6jmzl   2/2     Running   0          9m23s
k8s-runnerdeploy-vqfbd-knr9g   2/2     Running   0          9m23s
```

 Environment:
```
EKS 1.15
```
