### ISSUE TITLE
Convert manual secret step into Helm

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#241]
Hello,

I'm trying to put the github manager secret creation step into Helm and I am having problems. 

**Error**
```
Error: Environment variable read failed.
Error: Client creation failed. authentication failed: could not read private key: open : no such file or directory
```

**Template**
```yaml
{{- if or .Values.authSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.authSecret }}
  {{ $k }}: {{ $v | toString | b64enc }}
{{- end }} 
{{- end }} 
```

**values.yaml** (I've scrambled the values)
```yaml
apiVersion: v1
data:
  enabled: dHJ1ZQ==
  github_app_id: OasdadsNjU=
  github_app_installation_id: MS4yasdOsTasdsasaNDU5ZSswNw==
  github_app_private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM0g2V0NmYnB3VWY3NlBXbWZYZE5XVjA1R3NGeVJSdTRoODNCMVJhcW4wNjVxR2NJCkJVWHp4a3B4aFBNNFNnL3FQMi84c0JvVUV2SUk3cHZvVmFwL0syQ0hJZzZvWGZJa
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: sre-actions-controller-test
    meta.helm.sh/release-namespace: sre-actions-runner-system
  creationTimestamp: "2020-12-17T15:04:17Z"
  labels:
    app.kubernetes.io/instance: sre-actions-controller-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/version: 0.15.0
    helm.sh/chart: actions-runner-controller-1.0.0
  name: controller-manager
  namespace: sre-actions-runner-system
  resourceVersion: "143051925"
  selfLink: /api/v1/namespaces/sre-actions-runner-system/secrets/controller-manager
  uid: 24327f83-6dc0-3b35-8a79-2edb5f531f21
type: Opaque
```

Does `--from-file=` do anything special other than simply reading the content of a file? I've just`cat`ed my certificate and used the text. Google hasn't been much help.

```yaml
github_app_private_key: |
```

**Comment by mumoshu** [comment]
@callum-tait-pbx Just to be extra sure - you should use `--set-file authSecret.github_app_private_key=path/to/the/private/key/file` to use the content of the file, rather than its filename, as the value.

**Comment by mumoshu** [comment]
If you did put the content of the private key file into under

```
authSecret:
  github_app_private_key: |
    CONTENT
```

of your values.file, it should work.

It it doesn't, perhaps you'd better check your controller pods' volumes and volume mounts and verify that it does mount the `controller-manager` secret onto `/etc/actions-runner-controller`

**Comment by naphta** [comment]
Seeing a similar issue here, I'm setting content directly as described above (and in the docs) but I get the same
```
Error: Environment variable read failed.
Error: Client creation failed. authentication failed: could not read private key: open : no such file or directory
```
error.

Here's the helmfile I'm using: (or the important bit anyway)
```
  - name: actions-runner-controller
    namespace: github
    createNamespace: true
    chart: actions-runner-controller/actions-runner-controller
    version: 0.5.2
    values:
      - autoscaling:
          enabled: true
        authSecret:
          enabled: true
          github_app_id: 999999
          github_app_installation_id: 99999999
          github_app_private_key: |-
            -----BEGIN RSA PRIVATE KEY-----
            TRUNC
            -----END RSA PRIVATE KEY-----
```

We're running v1.18.2, I did a quick bit of debugging by switching out the manager image with busybox and I can see the files are there exactly where expected, and in a good format but they are links on disk. It's not an issue with following symbolic links is it? I've tried the [latest](https://hub.docker.com/layers/summerwind/actions-runner-controller/latest/images/sha256-77b48d9d38592292b3e2d582a3eddadd1d9663d01c25564c95431b336b5384ba?context=explore) and [canary](https://hub.docker.com/layers/summerwind/actions-runner-controller/canary/images/sha256-beb6ec8cbc2bf50bd4df763430346bb459139e842b1570597593eb4f6b404284?context=explore) images without much luck.
