### ISSUE TITLE
hostAliases for runner pods

### ISSUE THREAD

**Issue by reallydontask** [summerwind/actions-runner-controller#265]
Is there any way of getting hostAliases into the runner pods?

Essentially, what I'd like to achieve is to be able to modify the /etc/hosts file so that the runners can connect to jumpboxes with their current names

I've tried the following but to no avail, see below

Any suggestions?

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: ansible
  namespace: actions-runner-system
spec:
  replicas: 1
  template:   
    spec:  
      hostAliases:
       - ip: 10.10.1.1
         hostnames:
         - jumpbox    
      repository: ministryofjustice/ansible
      image: ministryofjustice/runner
      labels:
        - runner
```
