### ISSUE TITLE
/runner should be an emptyDir mount. Please fix the pod spec.

### ISSUE THREAD

**Issue by amigold** [summerwind/actions-runner-controller#274]
Hi all,

I'm running a fairly simple setup:
```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dbt-runner
spec:
  replicas: 1
  template:
    spec:
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      env: []
```

But 2 days ago the runner started failing with this error:
`/runner should be an emptyDir mount. Please fix the pod spec.`

I tried reinstalling everything with no success - any idea what I'm missing here?
