### ISSUE TITLE
[HorizontalRunnerAutoscaler] PercentageRunnersBusy is not working without organization specification

### ISSUE THREAD

**Issue by binoue** [summerwind/actions-runner-controller#292]
Hi! I tried to use HorizontalRunnerAutoscaler, but with `type: PercentageRunnersBusy` I encountered the following error below.
(With `type: TotalNumberOfQueuedAndInProgressWorkflowRuns`, everything works) 

```
2021-02-05T10:22:35.606Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "horizontalrunnerautoscaler", "request": "default/example-runner-deployment-autoscaler", "error": "enterprise, organization and repository are all empty"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88
```

I checked the code and I think the code below looks suspicious and is not fixed yet in master branch.
(`calculateReplicasByQueuedAndInProgressWorkflowRuns()` is checking `rd.Spec.Template.Spec.Repository`, but `calculateReplicasByPercentageRunnersBusy()` is not)
https://github.com/summerwind/actions-runner-controller/blob/master/controllers/autoscaling.go#L206-L207

The environment I used:
- k8s cluster: kind v0.10.0
- OS: ubuntu 20.04
- actions-runner-controller: v1.7.0

The manifests I used:
- https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
- https://github.com/summerwind/actions-runner-controller/releases/download/v0.17.0/actions-runner-controller.yaml
- runner-deployment.yaml
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
spec:
  replicas: 2
  template:
    spec:
      repository: XXX/XXXX
```
- horizontalrunnerautoscaler.yaml
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 60
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.3'
    scaleDownThreshold: '0.1'
    scaleUpFactor: '3'
    scaleDownFactor: '0.7'
    repositoryNames:
    - XXX/XXXXX
 ```

Thank you
