### ISSUE TITLE
Feature: Add Step Scaling Option For PercentageRunnersBusy Schema

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#305]
**Issue**
The `PercentageRunnersBusy` schema works great for my needs, organisation wide scaling without having to maintain a list of runners, instead we can manage workflow-to-runnerdeployment allocation through github labels rather than server side. This makes the overhead of supporting this solution much lower as it makes it much easier for the runnerdeployments to be self-serve for the developers. Scaling the actual runner count based on a percentage though is not ideal as your scaling very quickly starts to get excessively aggressive.

**Solution**
I'm basically thinking of AWS style step scaling where we would define the thresholds and then increment the runner count by the defined amount:

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 120
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpStepFactor: '2' 
    scaleDownStepFactor: '1'
```

In this example we would scale up the total number of runners by 2 when 75% of the runners were busy, conversly we would scale down the total number of runners by 1 at 30%. Extending the schema to include this alternative scaling style would be a great addition to this schema.

@ZacharyBenamram @mumoshu

**Comment by mumoshu** [comment]
@callum-tait-pbx Interesting idea! I agree it would be a good addition.

Instead of `scale(Up|Down)StepFactor`, can we add`scaleUpMin`, `scaleUpMax`, `scaleInMin`, `scaleInMax` for limiting number of added/removed runners?

The configuration gets more complex than your suggestion, but I think it serves broader use-cases, and fits nicely with  `TotalNumberOfQueuedAndInProgressWorkflowRuns` too.

**Comment by callum-tait-pbx** [comment]
It's up to you how you want to do it, I unfortunately can't write any Golang and don't get to use it at work so can't really make any head way with learning it sadly. I reasons I suggested the above construct though:
- In my view the `RunnerDeployment` top level attributes should be respected regardless of what scaling metric is useds i.e. `minReplicas`, `maxReplicas`, `scaleDownDelaySecondsAfterScaleOut`. I think overiding these in the metric is confusing and inconsistent design wise, the scaling metrics should be responsible with how to scale and by what amount, not what the constraints are for that `RunnerDeployment`.
- The `metrics` attribute is both plural in wording and a type list implying support for multiple scaling metrics to be used within a single `RunnerDeployment`. I think we don't actually support multiple metrics but if we continue to place the max/min replicas constraints at the global level then we don't break that (if multiple scaling metrics are supoprted) or don't create a complication down the road if that is something someone wants to introduce later.
- I would keep the yaml it as simple as possible as documenting it is actually quite hard and so keeping that simple keeps the overhead from issues raised lower.
- The solution is used by various people all who are used to the `minReplicas` and `maxReplicas` being a global attribute. Whilst changing that wouldn't be a breaking change it would be a break from the design philosophy and so confusing.

I can't too much comment on if it would be useful for the `TotalNumberOfQueuedAndInProgressWorkflowRuns` metric as it isn't a metric I use as I need org wide scaling without naming repos. I thought however the main characteristic of `TotalNumberOfQueuedAndInProgressWorkflowRuns ` was it scaled to the amount of workflows queued (up to the `maxReplicas` constraints) so scaling in a step fashion, whilst would work, isn't reallyt the intended style of scaling? Different metrics for different styles of scaling? I don't use it though so could be talking out of my arse here! :D

If you think there is value in having step style scaling across all metrics then by all means go for it! I personally however wouldn't break that design philosophy of:
- constraints are a global attributes 
- metrics are focused on their job of defining how to scale and by how much (not what the limits are)

**Comment by mumoshu** [comment]
@callum-tait-pbx Hey! Thank you so much for the detailed response. I think I agree fully with you.

Almost certainly I should have clarified that what I meant by e.g. `scaleUpMax` was to limit the number of replicas added in one step, rather than another threshold for total replicas.

That said, I would word `scaleUpStepFactor` as `scaleUpAmount` as it sounds a little more natural to me(opinion welcomed because I'm not a native English speaker). My `scaleUpMax` is should be worded `scaleUpAmountMax` if we make them consistent. Same for the scaleDown variant.

Anyways,

> I would keep the yaml as simple as possible as documenting it is actually quite hard and so keeping that simple will hopefully keep the amount of issues raised low (even if that makes the initial dev work longer).

This makes sense a lot! So I'd probably start with adding `scaleUpStepFactor / scaleUpAmount`. Hope you like it.

**Comment by callum-tait-pbx** [comment]
> Almost certainly I should have clarified that what I meant by e.g. scaleUpMax was to limit the number of replicas added in one step, rather than another threshold for total replicas.

I thought that might be the case, just wanted to be clear on my end

> That said, I would word scaleUpStepFactor as scaleUpAmount as it sounds a little more natural to me(opinion welcomed because I'm not a native English speaker). My scaleUpMax is should be worded scaleUpAmountMax if we make them consistent. Same for the scaleDown variant.

I mainly suggestted scaleUpStepFactor / scaleDownStepFactor as the original scope was just for the `PercentageRunnersBusy` schema so I was following the use of langauge there for consistency.

> This makes sense a lot! So I'd probably start with adding scaleUpStepFactor / scaleUpAmount. Hope you like it.

I've slept on it and I think the most logical way of doing the yaml is like this:

```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 1
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 120
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.3'
    scaleUpStepFactor: '2' 
    scaleDownStepFactor: '1'
```
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: example-runner-deployment-autoscaler
spec:
  scaleTargetRef:
    name: example-runner-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpStepFactor: '2' 
    scaleDownStepFactor: '1'
    repositoryNames:
    - summerwind/actions-runner-controller
