### ISSUE TITLE
Invalid resource name with helm chart 0.5.0

### ISSUE THREAD

**Issue by jeroen-s** [summerwind/actions-runner-controller#324]
`helm template actions-runner-org-controller .`

results in invalid name:

```
# Source: actions-runner-controller/templates/auth_proxy_service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: actions-runner-controller-0.5.0
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: actions-runner-org-controller
    app.kubernetes.io/managed-by: Helm
  name: actions-runner-org-controller-actions-runner-controller-metrics-service
  namespace: default
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/name: actions-runner-controller
    app.kubernetes.io/instance: actions-runner-org-controller
```
