### ISSUE TITLE
Feature: Make `RepositoryNames` Atttribute Optional for RunnerDeployments Back by HRA

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#333]
Initially discussed in https://github.com/summerwind/actions-runner-controller/pull/303, see for more details. Creating a seperate feature issue so it doesn't get lost @mumoshu /

**Problem**

At the moment you need to maintain a `RepositoryNames` list in both the `RunnerDeployment` as well as the `HorizontalRunnerAutoscaler` that backs it. This is non-optimal for obvious reasons

**Solutions**

1. Make the RepositoryNames list optional with RunnerDeployment and mandatory with HRAs. They can be included in RunnerDeployment so you can run sets of RunnerDeployments without a HRA if you really want but excluded if your RunnerDeployment is backed by a HRA
2.  Or do it the other way, remove RepositoryNames from the HRA spec and make it pull its list from the RunnerDeployment it is targeting instead. If this approach was taken I wouldn't even make RepositoryNames part of the HRA spec, from my knowledge of the solution I don't see any benefit being able to define the RepositoryNames list twice? Even if you could point 1 HRA at multiple RunnerDeployments I would still make it get its list from all the associated targets instead of having to maintain its own list.

Option 1 was preferred because `GitHub API doesn't provide us the way to efficiently calculate which repository uses which organizational runner and how busy they are.`

**Comment by callum-tait-pbx** [comment]
@mumoshu this is legit issue. Please add the `enhancement` label and remove the stale label so the bot doens't kill it.

**Comment by mumoshu** [comment]
@callum-tait-pbx Hey! I was rereading the code and the option 1 is already implemented. That is, as long as the targeted RunnerDeployment has `.Spec.Template.Spec.Repository` defined, `HRA.Spec.Metrics[].RepositoryNames` is ignored. 

`HRA.Spec.Metrics[].RepositoryNames` is used when RunnerDeployment is targeted to anything other than Repository, like Enterprise and Organization(It's primary targeting Organization and I'm not sure if it actually works with Enterprise though).

**Comment by callum-tait-pbx** [comment]
> @callum-tait-pbx Hey! I was rereading the code and the option 1 is already implemented. That is, as long as the targeted RunnerDeployment has .Spec.Template.Spec.Repository defined, HRA.Spec.Metrics[].RepositoryNames is ignored.

Wonderful! Another update to the docs then 😫 😆 

> HRA.Spec.Metrics[].RepositoryNames is used when RunnerDeployment is targeted to anything other than Repository, like Enterprise and Organization(It's primary targeting Organization and I'm not sure if it actually works with Enterprise though).

Sorry could you clarify this paragraph for me? `HRA.Spec.Metrics[].RepositoryNames` is used when the targeted `RunnerDeployment` isn't targeting repositories. Surely `RepositoryNames` is specifically a list of repositories?

**Comment by mumoshu** [comment]
> Sorry could you clarify this paragraph for me? HRA.Spec.Metrics[].RepositoryNames is used when the targeted RunnerDeployment isn't targeting repositories. Surely RepositoryNames is specifically a list of repositories?

@callum-tait-pbx Yes. In other words, `RepositoryNames` are only valid for a HRA of `TotalNumberOfQueuedAndInProgressWorkflowRuns` against organizational or enterprise RunnerDeployment.

https://github.com/actions-runner-controller/actions-runner-controller/blob/588872a31649b3021d93d031e99e722674d6399b/controllers/autoscaling.go#L108

**Comment by callum-tait-pbx** [comment]
You're right! Just gone through the API reference docs and I don't see how we could do it.

Could you add the `enhancement` label for searchability, I'll update the docs with the information about the attribute being optional and we can then close off this issue. 

I don't know if it's worth having a label for `not currently possible` or something? Again for searchability down the line.

**Comment by bigjew92** [comment]
> (...I'm not sure if it actually works with Enterprise though).

@mumoshu to this point, in bold, I don't believe this behavior is working with Enterprise.


```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      enterprise: my-enterprise
      labels:
        - controller-runner
      containers:
      - name: runner
        imagePullPolicy: IfNotPresent
        env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
spec:
  scaleDownDelaySecondsAfterScaleOut: 120
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 0
  maxReplicas: 10
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '1'
    scaleDownThreshold: '1'
    scaleUpAdjustment: 1
    scaleDownAdjustment: 1
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - org1/repo1
    - org2/repo2
```

I am seeing these errors in the controller logs

```
2022-01-28T21:43:56.510Z	ERROR	actions-runner-controller.horizontalrunnerautoscaler	Could not compute replicas	{"horizontalrunnerautoscaler": "actions-runner-system/runner-deployment-autoscaler", "error": "asserting runner deployment spec to detect bug: spec.template.organization should not be empty on this code path"}
github.com/actions-runner-controller/actions-runner-controller/controllers.(*HorizontalRunnerAutoscalerReconciler).Reconcile
	/workspace/controllers/horizontalrunnerautoscaler_controller.go:99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2022-01-28T21:43:56.510Z	ERROR	controller-runtime.manager.controller.horizontalrunnerautoscaler-controller	Reconciler error	{"reconciler group": "actions.summerwind.dev", "reconciler kind": "HorizontalRunnerAutoscaler", "name": "runner-deployment-autoscaler", "namespace": "actions-runner-system", "error": "asserting runner deployment spec to detect bug: spec.template.organization should not be empty on this code path"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214
2022-01-28T21:43:56.510Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"HorizontalRunnerAutoscaler","namespace":"actions-runner-system","name":"runner-deployment-autoscaler","uid":"0e1816c6-ab8b-4478-9bfc-78cb81da4d4c","apiVersion":"actions.summerwind.dev/v1alpha1","resourceVersion":"513551317"}, "reason": "RunnerAutoscalingFailure", "message": "asserting runner deployment spec to detect bug: spec.template.organization should not be empty on this code path"}
```

Specifically, I am trying to scale from 0, like mentioned in the docs. Without the metrics `TotalNumberOfQueuedAndInProgressWorkflowRuns`, scaling seems to work.
