### ISSUE TITLE
Using a Kubernetes service account token to authenticate to the Kubernetes cluster running an action

### ISSUE THREAD

**Issue by japsu** [summerwind/actions-runner-controller#368]
I figured I would run the self hosted runner using a service account and give that service account the required RBAC to be able to deploy into the same cluster running the self hosted runner:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: con2
spec:
  replicas: 2
  template:
    spec:
      organization: con2
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      serviceAccountName: actions-runner
      automountServiceAccountToken: true
      volumeMounts:
       - mountPath: /runner
         name: runner
      volumes:
       - emptyDir: {}
         name: runner      

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner

---
# NOTE: this policy is still WIP, we're not even there yet
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["deployments", "services"]
  verbs: ["get", "watch", "list", "update", "delete"]
- apiGroups: ["networking.k8s.io/v1", "extensions/v1"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: actions-runner
  apiGroup: rbac.authorization.k8s.io
```

However, this is not yet enough to convey Kubernetes authentication to the actions. There's so many layers of containers here at play it's a sandockerwich!

The action runners have a `/var/run/secrets/kubernetes.io/serviceaccount from actions-runner-token-s9s8w (ro)` volume mount. How would I go about pushing this down to actions running on the self hosted runner?

Example workflow https://github.com/con2/redirects/blob/main/.github/workflows/deploy.yaml

Using this action https://github.com/con2/emskaffolden-action

Helm chart version `actions-runner-controller-0.6.1`.

**Comment by erikkn** [comment]
Hi @japsu ! Out of curiosity, what is it exactly you are trying to achieve? This sounds interesting :)

**Comment by japsu** [comment]
I have a Kubernetes cluster running behind a firewall. I'm trying to deploy to it using Github Actions.

One obvious way to go about this would be to open the k8s API to GitHub and put a kubeconfig in a secret, but that feels insecure.

Instead, I figured I could run a self hosted runner in the cluster, authenticate it to the cluster using a service account token and authorize it using RBAC.

But it seems it's not enough to authenticate the runner pods, because they run actions in separate containers (DinD?). I would need to get `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` env vars and `/var/run/secrets/kubernetes.io/serviceaccount` directory mounted inside the action.

**Comment by japsu** [comment]
Also this isn't particular to [con2/emskaffolden](https://github.com/con2/emskaffolden) or [GoogleContainerTools/skaffold](https://github.com/GoogleContainerTools/skaffold), `emskaffolden` runs `skaffold` which runs `kubectl` in the end.

**Comment by mumoshu** [comment]
@japsu Hey!

> they run actions in separate containers (DinD?)

In the default setup(=`dockerWithinRunnerContainer: false`), yes.

I believe `emskaffolden-action` needs to execute `docker-run` with `-v /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount`, which isn't possible with [the docker-based action you're using](https://github.com/con2/emskaffolden-action/blob/8511f008e7120c2aafb4b0101e85ec444e70643d/action.yml#L3-L4). Probably you need to rewrite your action in js/typescript.

Another way would be to write a `setup-emskaffolden` action to install `emskaffolden` binary onto the runner container and run it via a `run` step. This results in the workflow executing the command without `docker`, so that the command is able to access `/var/run/secrets/kubernetes.io/serviceaccoun` without any gotcha.

**Comment by mumoshu** [comment]
Actually I prefer the latter. [Here's one of my `setup` actions for your reference](https://github.com/variantdev/setup-variant) and [one from Azure for kubectl](https://github.com/Azure/setup-kubectl/blob/master/src/run.ts).

**Comment by japsu** [comment]
Didn't think of that approach! I'll try it out. It's a bit involved because `emskaffolden` is written in Python so it doesn't come as a single file, but I think I can manage it with a `virtualenv`.

**Comment by japsu** [comment]
Or I could split it into running `emrichen` templating a separate action and then just plain `kubectl`, but then I'd lose `skaffold`'s excellent support for waiting for the deployment to stabilize before reporting success. Then again, I could use https://github.com/marketplace/actions/deploy-to-kubernetes-cluster instead of plain `kubectl` to do the deplayment and waiting for it to complete. 🤔

**Comment by mumoshu** [comment]
@japsu Perhaps you don't even need to struggle with `virutalenv`? I thought our runner image contains python3 and the runner pod is recreated on each workflow run. You don't need to worry about installing python or some action in a workflow run affecting another workflow run's python environment, if that's your concern.

**Comment by japsu** [comment]
Yeah, could probably just

```yaml
- run: pip3 install emskaffolden
```

though that would get executed on every run. Was thinking if I had a prepackaged virtualenv somewhere, I could copy it over without doing the dependency resolution etc. every time.

**Comment by japsu** [comment]
Thanks for the pointers! Got the first PoC working:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: con2
spec:
  replicas: 2
  template:
    spec:
      organization: con2
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      serviceAccountName: actions-runner
      automountServiceAccountToken: true
      volumeMounts:
       - mountPath: /runner
         name: runner
      volumes:
       - emptyDir: {}
         name: runner      

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner

---
# NOTE: this policy is still WIP, we're not even there yet
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "extensions"] # "" indicates the core API group
  resources: ["deployments", "services", "configmaps", "secrets", "ingresses"]
  verbs: ["get", "watch", "list", "patch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner
subjects:
- kind: ServiceAccount
  name: actions-runner
  namespace: actions-runner-system
roleRef:
  kind: ClusterRole
  name: actions-runner
  apiGroup: rbac.authorization.k8s.io
```

```yaml

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
      - uses: con2/emskaffolden-action@main
        with:
          args: -E production
      - run: kubectl apply -f kubernetes/template.compiled.yaml -n redirects
 ```
