### ISSUE TITLE
[v0.17.0] enterprise, organization and repository are all empty 

### ISSUE THREAD

**Issue by Puneeth-n** [summerwind/actions-runner-controller#375]
Hi, I am constantly getting an error. PFB my config

```
2021-03-05T19:09:06.343Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "horizontalrunnerautoscaler", "request": "ci/comtravo-github-actions-deployment-autoscaler", "error": "enterprise, organization and repository are all empty"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
```

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: bar-github-actions-deployment
  namespace: foo
spec:
  template:
    spec:
      image: harbor.infra.bar.com/cache/bar/actions-runner:v2.276.1
      imagePullPolicy: Always
      repository: bar/baz
      serviceAccountName: some-sa
      securityContext:
        fsGroup: 1447
      resources:
        limits:
          cpu: "1"
          memory: "4Gi"
        requests:
          cpu: "1m"
          memory: "256Mi"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: bar-github-actions-deployment-autoscaler
  namespace: foo
spec:
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    name: bar-github-actions-deployment
  minReplicas: 4
  maxReplicas: 100
  metrics:
  - type: PercentageRunnersBusy
    repositoryNames:
    - bar/baz
    scaleUpThreshold: '0.75'    # The percentage of busy runners at which the number of desired runners are re-evaluated to scale up
    scaleDownThreshold: '0.3'   # The percentage of busy runners at which the number of desired runners are re-evaluated to scale down
    scaleUpFactor: '1.4'        # The scale up multiplier factor applied to desired count
    scaleDownFactor: '0.7'      # The scale down multiplier factor applied to desired count
```
