### ISSUE TITLE
Allow github private key to be an environment variable

### ISSUE THREAD

**Issue by TimJones** [summerwind/actions-runner-controller#382]
I use an external secrets manager (specifically [Hashicorp Vault](https://www.vaultproject.io/) with [BanzaiCloud bank-vaults mutator](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/)) which means I set up my secrets as references to an endpoint in Vault, and the real values get injected into the pod on startup.

This was giving me issues with actions-runner-controller until I realised the `github_app_private_key` was not being read from an environment variable but mounted as a file. I can work around this, but I think it would be helpful to add a way to configure this as an actual environment variable.

**Comment by mumoshu** [comment]
@TimJones Hey! Thanks for the feedback.

I've re-read code around this and was a bit surprised to see how it works today!

Probably we can add another environment variable like `GITHUB_APP_PRIVATE_KEY_DATA` that directly accepts the content of the private key, rather than the path to it.

Out of curiosity, which deployment method are you using, K8s manifests or Helm? For helm, we might need to update our chart as well to support the new envvar. But probably there's no way to use something like bank-vaults in combination with the helm chart that you won't care?

**Comment by mumoshu** [comment]
@TimJones Please see #382. I just made the envvar optionally accept the content of the private key. Would it work for you?

**Comment by TimJones** [comment]
> which deployment method are you using, K8s manifests or Helm?

We use Kustomize whenever possible to give us better control of the resultant manifests

> For helm, we might need to update our chart as well to support the new envvar.

And that's why 😄 

> But perhaps there's no way to use something like bank-vaults in combination with the helm chart so you won't care?

It always depends on the chart. The Bank-Vault mutator works on the pod itself, using annotations and specially formatted environment variables to replace the 'pointer' to the secret with the actual secret data itself. As long as the chart supports annotations for the *pods* then it's easy to apply.

I'm happy to test the new code, but it looks as if the 0.8.0 image wasn't built or pushed to dockerhub. I can build & push one myself but I thought you should know.

**Comment by TimJones** [comment]
@mumoshu Can confirm that the 0.8.0 runner canary image works great with the private key being in `GITHUB_APP_PRIVATE_KEY`! Thanks!

For future searches, I patch the official manifests using the following Kustomize configuration

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - https://github.com/summerwind/actions-runner-controller/releases/download/v0.17.0/actions-runner-controller.yaml

secretGenerator:
  - name: controller-manager
    options:
      disableNameSuffixHash: true
    literals:
      - github_app_id=...snip...
      - github_app_installation_id=...snip...
      - github_app_private_key=...snip...

patches:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
      namespace: actions-runner-system
    spec:
      template:
        spec:
          containers:
            - name: manager
              env:
                - name: GITHUB_APP_PRIVATE_KEY
                  value: ""
                  valueFrom:
                    secretKeyRef:
                      key: github_app_private_key
                      name: controller-manager
                      optional: true
                      
# Just while testing the 0.8.0 pre-release
images:
  - name: summerwind/actions-runner-controller
    newTag: canary
```
