### ISSUE TITLE
Network Timeouts

### ISSUE THREAD

**Issue by michaelst** [summerwind/actions-runner-controller#393]
When running a docker build network requests made inside the Dockerfile are blocked. It pulls the FROM image just fine. I'm not sure what info would help debug this so just let me know.

**Comment by mumoshu** [comment]
@michaelst Hey! Could you share your workflow yaml file that contains the job running `docker build`? Probably that would help us reproduce/investigate the issue.

**Comment by michaelst** [comment]
Here is the workflow file, it works up to the docker build step on `mix local.hex --force` with this error 
```
Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.
``` 
I've been doing some more testing around that and it actually works to curl that url. This flow works on regular GitHub Actions. From looking at tickets with similar issues it has been a DNS issue. Is the dind image doing something weird with DNS?

```
name: Deploy
on:
  push:
    branches:
      - master

jobs:
  backend:
    name: Backend
    runs-on: [self-hosted, Linux, ARM64]

    defaults:
      run:
        working-directory: backend

    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    steps:
      - uses: actions/checkout@main
          
      - name: GCP Authentication
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 -d > google_credentials.json
          gcloud auth activate-service-account --key-file google_credentials.json --quiet
          gcloud auth configure-docker us.gcr.io --quiet

      - name: Build
        run: |    
          docker build -t us.gcr.io/cloud-57/spendable-api:${GITHUB_SHA} -f .devops/Dockerfile .
          docker push us.gcr.io/cloud-57/spendable-api:${GITHUB_SHA}
```

Here is my Dockerfile
```
FROM elixir:1.11-slim AS build

ENV MIX_ENV=prod \
    LANG=C.UTF-8

RUN mkdir /app
WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config/config.exs config/prod.exs ./config/
RUN mix do deps.get, deps.compile

COPY lib lib
COPY priv priv
RUN mix compile

COPY config/releases.exs ./config/
RUN mix release

FROM ubuntu:20.04 AS release

ENV LANG=C.UTF-8

RUN apt-get update \
  && apt-get install -y --no-install-recommends openssl \
  && useradd --create-home -u 1000 app \
  && rm -rf /var/lib/apt/lists/*

USER app
WORKDIR /home/app

COPY --from=build --chown=app:app /app/_build/prod/rel/spendable ./
COPY --chown=app:app .devops/entrypoint.sh .
CMD ["./entrypoint.sh"]
```

**Comment by mumoshu** [comment]
@michaelst Thanks! Does `curl https://repo.hex.pm/installs/hex-1.x.csv` work on one of your runner pods (not controller pods) work? Probably you could try `kubectl exec -it` into a pod and manually run the curl command. If it fails, I think enabling verbose logs on curl gives more information. If it's a DNS issue, you should be able to reproduce it without `mix`.

**Comment by michaelst** [comment]
So the curl did work when inside of the Dockerfile, which container in the runner pod should I do that, it doesn't work in the docker container as it doesn't have curl installed and limited shell access.

I tried an alternative way with git in the Dockerfile and got this error from git
```
fatal: unable to access 'https://github.com/hexpm/hex.git/': server certificate verification failed. CAfile: none CRLfile: none
```

**Comment by michaelst** [comment]
That was because I needed to install ca-certificates, oops

**Comment by michaelst** [comment]
I'm also getting random timeouts on `apt-get update`

```
Get:5 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
46
Err:5 http://security.debian.org/debian-security buster/updates InRelease
47
  Connection failed [IP: 151.101.66.132 80]
48
Fetched 7919 kB in 60s (132 kB/s)
49
Reading package lists...
50
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Connection failed [IP: 151.101.66.132 80]
51
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mumoshu** [comment]
@michaelst I think this kind of issue can happen when your network requires smaller MTU size. If you think it worth trying, would you mind trying https://github.com/summerwind/actions-runner-controller/pull/385 and try setting it to lower to adapt your environment? The feature is available in the `canary` tag of our controller image and the latest chart.

**Comment by michaelst** [comment]
Looks like that is my problem as eth0 has an MTU of 1450, however, how do I use the canary flag, I don't see that on docker and the latest docker image is 7 days ago, I am using the 0.9.0 version chart.

**Comment by mumoshu** [comment]
@michaelst Thanks for confirming. Re docker image tag, it's about `actions-runner-controller` rather than `actions-runner`. The former is for the controller and the latter is for runners created and managed by the runner. MTU is configured by the controller at the time of each runner is created, so you should update the controller image, rather than runner's.

**Comment by michaelst** [comment]
I'm getting this error with the canary image installed trying to setup the RunnerDeployment
```
failed to create resource: Internal error occurred: failed calling webhook "mutate.runnerdeployment.actions.summerwind.dev": Post "https://github-runner-controller-actions-runner-controller-webhook.github-runner.svc:443/mutate-actions-summerwind-dev-v1alpha1-runnerdeployment?timeout=30s": context deadline exceeded

**Comment by mumoshu** [comment]
@michaelst Would you mind removing `mutatingwebhookconfiguration` and `validatingwebhookconfiguration` temporarily to see if it resolves the issue? If not, `kubectl -n $NS logs deploy/actions-runner-controller` would possibly show some useful error messages.

**Comment by michaelst** [comment]
ok deleting those allowed the pods to deploy, however, docker0 still has 1500
```
docker0   Link encap:Ethernet  HWaddr 02:42:20:D5:06:0F  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

and I do see this configured on the pod now 
```
- name: docker
      image: 'docker:dind'
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKERD_ROOTLESS_ROOTLESSKIT_MTU
          value: '1450'
```
