### ISSUE TITLE
Passing IRSA to docker builds

### ISSUE THREAD

**Issue by Puneeth-n** [summerwind/actions-runner-controller#433]
I am trying to build docker images and in some docker images, I have some aws cli commands. I was wondering if there was any way of passing the IRSA to the docker daemon so that it could execute aws cli commands during docker build.

Please find below a sample Dockerfile

```
FROM python:3.8
...
RUN python -c "import nltk; nltk.download('punkt')"

ARG CI
ENV AWS_DEFAULT_REGION=eu-west-1
ENV AWS_REGION=eu-west-1
RUN if [ "true" = "$CI" ] ; then make s3_sync ; else echo "Not syncing with s3 because running outside CI" ; fi
COPY ./js/lib/passport /usr/src/app/js/lib/passport
...
```

**Comment by callum-tait-pbx** [comment]
You should just be able to map them into the container like this:

```yaml
name: IRSA in container

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: [ 'self-hosted', 'Linux' ]
    container: 
      image: amazon/aws-cli
      env:
        AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        AWS_ROLE_ARN: arn:aws:iam::%AWS_ACCOUNT_ID%:role/%YOUR_IRSA_ROLE%
      volumes:
        - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token
    steps:
    - uses: actions/checkout@v2
    - name: aws
      run: |
        aws s3 ls
```
