### ISSUE TITLE
Docker daemon is not running in "actions-runner-dind" image

### ISSUE THREAD

**Issue by int128** [summerwind/actions-runner-controller#461]
I'm getting the following error when I run `docker build` in a workflow (maybe since a few hours ago).

```
error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Here is my config:

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myrepo
spec:
  template:
    spec:
      # runner with dind
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      # using IRSA
      serviceAccountName: myrepo
      securityContext:
        fsGroup: 1447
```

Recently `summerwind/actions-runner-dind` image has been updated: https://hub.docker.com/r/summerwind/actions-runner-dind/tags. Is #438 related to this issue?

Thanks.
