### ISSUE TITLE
Controller creates a lot of runners

### ISSUE THREAD

**Issue by vterdunov** [summerwind/actions-runner-controller#467]
Hi, thanks for the project.

I faced with issue after the operator was updated using helm chart 0.10.4->0.11.0.
Controller started to create a lot of runners pods.
```
k -n actions-runner-system get po | wc -l
213
```

I have two runner deployemnts and corresponding autoscalers. There are identical, just for different repos. E.g:
```yaml
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: product-x-backend-runners
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: my-org/my-repo
      labels:
      - k8s

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: product-x-backend-runners-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: product-x-backend-runners
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - my-org/my-repo
```
