### ISSUE TITLE
Volume mounted twice, cause controller to fail

### ISSUE THREAD

**Issue by kuuji** [summerwind/actions-runner-controller#48]
Not sure if it's the only issue. I've been trying to get volume + volumeMount to work to inject a secret.

Here's what I'm getting in the logs

```

 manager 2020-04-29T14:47:57.249Z    ERROR    controllers.Runner    Failed to create pod resource    {"runner": "default/docker-images-runners-98kht-xffvd", "error": "Pod \"docker-images-runners-98kht-xffvd\" is
  invalid: [spec.volumes[1].name: Duplicate value: \"artifactory-secret-volume\", spec.containers[0].volumeMounts[0].name: Not found: \"work\", spec.containers[0].volumeMounts[1].name: Not found: \"docker\", spe
 c.containers[1].volumeMounts[0].name: Not found: \"work\", spec.containers[1].volumeMounts[1].name: Not found: \"docker\"]"}
```

See my runnerDeployment below

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: docker-images-runners
spec:
  replicas: 2
  template:
    spec:
      repository: myorg/docker-images
      labels:
        - custom-label
      volumes:
      - name: artifactory-secret-volume
        secret:
          secretName: artifactory-secret
      volumeMounts:
      - name: artifactory-secret-volume
        readOnly: true
        mountPath: "/etc/artifactory-secret-volume"
```

I believe this happens because of 

https://github.com/summerwind/actions-runner-controller/blob/b96979888c0bf4075360b4c6858c8c5fe8fee00d/controllers/runner_controller.go#L363

If I'm reading this properly, it's appending the same thing twice?
I haven't tried a fix yet. 

edit:

My guess is that it should be this instead

```
pod.Spec.Volumes = append(pod.Spec.Volumes , runner.Spec.Volumes...)
```
