### ISSUE TITLE
Could not run RunnerDeployment with organization setting

### ISSUE THREAD

**Issue by rezmuh** [summerwind/actions-runner-controller#60]
Hi, I just installed this for my organization and I already saw that the runners are running:

```
› kubectl get runner                                                                                                                                                 
NAME                        ORGANIZATION   REPOSITORY   LABELS   STATUS
github-runner-dn442-25m4h   lifepal                              Running
github-runner-dn442-btkzd   lifepal                              Running
github-runner-dn442-pxgh6   lifepal                              Running
github-runner-dn442-xzd2k   lifepal                              Running
```

And the runners are registered within the organization as well as shown below.

<img width="762" alt="Screen Shot 2020-06-21 at 10 43 17" src="https://user-images.githubusercontent.com/1204244/85216215-123dac80-b3ac-11ea-9648-eea40dd5c8cf.png">

And this is how I installed the runners:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner
spec:
  replicas: 4
  template:
    spec:
      organization: <my org>
```
However, the actions could not be run. This was the error I got from the action log

<img width="1093" alt="Screen Shot 2020-06-21 at 10 39 13" src="https://user-images.githubusercontent.com/1204244/85216226-297c9a00-b3ac-11ea-900b-4e9f8f0eaeb3.png">

It looks like I must have missed a setting somewhere?

**Comment by mumoshu** [comment]
@rezmuh Hey! Maybe there's any issue in your workflow definition? Would u mind sharing it?

To me, a docker run like this one, in a job on a self-hosted runner, just works: https://github.com/mumoshu/runnertest/blob/master/.github/workflows/test.yaml#L18

**Comment by rezmuh** [comment]
Hi, this is the workflow definition I tried to run.

```
name: pull-request

on:
  pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    container: rust:1.43.0

    services:
      db:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        submodules: 'recursive'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install rustfmt
      run: rustup component add rustfmt --toolchain 1.43.0-x86_64-unknown-linux-gnu
    - name: Build binary
      run: cargo build
    - name: Run tests
      run: cargo test
```
