### ISSUE TITLE
RunnerDeployment isn't recognizing min and max replicas

### ISSUE THREAD

**Issue by avik-so** [summerwind/actions-runner-controller#65]
First, thank you very much for this controller and your readme, setup was a breeze.

Initially, I set up a basic runner, everything worked well. Then I deleted it and ran applied this RunnerDeployment
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: oncehub-github-runner-controller
spec:
  minReplicas: 1
  maxReplicas: 12
  scaleDownDelaySecondsAfterScaleUp: 1m
  template:
    spec:
      organization: my-org
```
After running this and waiting a few minutes, I saw no pods and no runners.

So I modified the file to this:
```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: oncehub-github-runner-controller
spec:
  replicas: 3
  minReplicas: 1
  maxReplicas: 12
  scaleDownDelaySecondsAfterScaleUp: 1m
  template:
    spec:
      organization: my-org
```
This successfully set up 3 runners, and 2 are idle. But it's not scaling down to 1 runner.

What am I doing wrong?
