### ISSUE TITLE
No runners

### ISSUE THREAD

**Issue by kaykhancheckpoint** [summerwind/actions-runner-controller#67]
Hi

My first time setting this up, unfortunately it's showing that i have no runners.

```
kay@khan:~/checkpoint/self-hosted-runner$ kubectl get runners
No resources found in default namespace.
```

**Setup**:

```
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml
kubectl apply -f https://github.com/summerwind/actions-runner-controller/releases/latest/download/actions-runner-controller.yaml
kubectl create secret generic controller-manager \
    -n actions-runner-system \
    --from-literal=github_token=<redacted>
kubectl apply -f runner.yml
```

**runner.yml**

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: checkpoint-runner
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleUp: 1m
  template:
    spec:
      organization: <redacted>

```

I did not come across any errors/problems in the setup. So what have i done wrong, why are there no runners (even tho minReplicas is set to 1)

Ah i forgot to actually add a kind: Runner. So now i have

```
kay@khan:~/checkpoint/self-hosted-runner$ kubectl get runners
NAME                ORGANIZATION   REPOSITORY   LABELS   STATUS
checkpoint-runner   <redacted>                         Running
```

Can someone confirm that i need both Runner and RunnerDeployment?

because i updated min replicas to 2 like in the example but i still only have (like above)
