### ISSUE TITLE
Runner job interrupted due to token refresh

### ISSUE THREAD

**Issue by tbl-harmoney** [summerwind/actions-runner-controller#74]
When runners are reconciled, a termination signal is triggered and running jobs are stopped. 
![summerwind-0](https://user-images.githubusercontent.com/65944949/87394523-30b05580-c5b0-11ea-86f7-5a46c7a80d23.png)

Using a custom image based on the latest release (2020-07-13) [summerwind/actions-runner](https://hub.docker.com/layers/summerwind/actions-runner/latest/images/sha256-bd29a9f68267b2aac50ccb4959ade881bdd008e4b89fc341e7150a9130eb6644).

![summerwind-1](https://user-images.githubusercontent.com/65944949/87397344-80911b80-c5b4-11ea-90df-637a9d3a6cf2.png)

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd-test-runners
  labels:
    name: ci-cd-test-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: test-runner
  namespace: ci-cd-test-runners
spec:
#  minReplicas: 1
#  maxReplicas: 12
  replicas: 3
  template:
    spec:
      repository: acme/acme
      labels:
        - test
      tolerations:
        - key: runner-taint
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        cloud.google.com/gke-nodepool: ci-cd-test-runners
      ImagePullPolicy: Always
      image: gcr.io/acme/ci-cd-runner/test:latest
      resources:
        limits:
          cpu: "2.0"
          memory: "8Gi"
        requests:
          cpu: "1.5"
          memory: "5Gi"
```
