### ISSUE TITLE
Question: auto scaling clarification, how to achieve quick scaling for org runners?

### ISSUE THREAD

**Issue by callum-tait-pbx** [summerwind/actions-runner-controller#87]
I'm managed to get the solution up with a organisational runner with workflows successfully working it it, I'm very impressed with the solution so far. I am now trying to get the autoscaling aspects working and am struggling a bit. Is my understanding correct?

The docs state ```In the below example, actions-runner checks for pending workflow runs for each sync period, and scale to e.g. 3 if there're 3 pending jobs at sync time.```. As a result if I want the number of runners to scale quickly I need to set this period as low as possible? Is 1 minute the shortest sync period possible. It seems to me that a quick scaling convergence time would be the default experience most people would want so I'm sure I am miss understanding something?

My deployment is just the default stack deployed with the removal of the namespace creation (would love a Helm chart for all this as we are a Helm shop). My runner yaml is:

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: serverless-deployments-runner
spec:
  organization: my-org-name
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: serverless-deployments-deployment
spec:
  template:
    spec:
      organization: my-org-name
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: serverless-deployments-autoscaler
spec:
  scaleTargetRef:
    name: serverless-deployments-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - summerwind/actions-runner-controller
```
